export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_EXPIRES_IN = 'EXPIRES_IN';
export const SET_LOGIN = 'SET_LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_LOGOUT = 'SET_LOGOUT';

export const GET_SONG_RECOMMENDATION_REQUEST =
  'GET_SONG_RECOMMENDATION_REQUEST';
export const GET_SONG_RECOMMENDATION_SUCCESS =
  'GET_SONG_RECOMMENDATION_SUCCESS';
export const GET_SONG_RECOMMENDATION_FAILURE =
  'GET_SONG_RECOMMENDATION_FAILURE';

export const GET_USERS_PLAYLIST_REQUEST = 'GET_USERS_PLAYLIST_REQUEST';
export const GET_USERS_PLAYLIST_SUCCESS = 'GET_USERS_PLAYLIST_SUCCESS';
export const GET_USERS_PLAYLIST_FAILURE = 'GET_USERS_PLAYLIST_FAILURE';

export const GET_USERS_TOP_ARTISTS_REQUEST = 'GET_USERS_TOP_ARTISTS_REQUEST';
export const GET_USERS_TOP_ARTISTS_SUCCESS = 'GET_USERS_TOP_ARTISTS_SUCCESS';
export const GET_USERS_TOP_ARTISTS_FAILURE = 'GET_USERS_TOP_ARTISTS_FAILURE';

export const GET_USERS_TOP_TRACKS_REQUEST = 'GET_USERS_TOP_TRACKS_REQUEST';
export const GET_USERS_TOP_TRACKS_SUCCESS = 'GET_USERS_TOP_TRACKS_SUCCESS';
export const GET_USERS_TOP_TRACKS_FAILURE = 'GET_USERS_TOP_TRACKS_FAILURE';

export const PLAY_CONTEXT_REQUEST = 'PLAY_CONTEXT_REQUEST';
export const PLAY_CONTEXT_SUCCESS = 'PLAY_CONTEXT_SUCCESS';
export const PLAY_CONTEXT_FAILURE = 'PLAY_CONTEXT_FAILURE';

export const PAUSE_CONTEXT_REQUEST = 'PAUSE_CONTEXT_REQUEST';
export const PAUSE_CONTEXT_SUCCESS = 'PAUSE_CONTEXT_SUCCESS';
export const PAUSE_CONTEXT_FAILURE = 'PAUSE_CONTEXT_FAILURE';

export const GET_ME_REQUEST = 'GET_ME_REQUEST';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILURE = 'GET_ME_FAILURE';

export const SEARCH_ARTIST_REQUEST = 'SEARCH_ARTIST';
export const SEARCH_ARTIST_SUCCESS = 'SEARCH_ARTIST_SUCCESS';
export const SEARCH_ARTIST_FAILURE = 'SEARCH_ARTIST_FAILURE';

export const SEARCH_NEXT_ARTIST_REQUEST = 'SEARCH_NEXT_ARTIST';
export const SEARCH_NEXT_ARTIST_SUCCESS = 'SEARCH_NEXT_ARTIST_SUCCESS';
export const SEARCH_NEXT_ARTIST_FAILURE = 'SEARCH_NEXT_ARTIST_FAILURE';

export const SEARCH_TRACK_REQUEST = 'SEARCH_TRACK';
export const SEARCH_TRACK_SUCCESS = 'SEARCH_TRACK_SUCCESS';
export const SEARCH_TRACK_FAILURE = 'SEARCH_TRACK_FAILURE';

export const SEARCH_NEXT_TRACK_REQUEST = 'SEARCH_NEXT_TRACK';
export const SEARCH_NEXT_TRACK_SUCCESS = 'SEARCH_NEXT_TRACK_SUCCESS';
export const SEARCH_NEXT_TRACK_FAILURE = 'SEARCH_NEXT_TRACK_FAILURE';

export const GET_GENRE_REQUEST = 'GET_GENRE_REQUEST';
export const GET_GENRE_SUCCESS = 'GET_GENRE_SUCCESS';
export const GET_GENRE_FAILURE = 'GET_GENRE_FAILURE';

export const SET_ARTIST_RESULT = 'SET_ARTIST_RESULT';
export const SET_TRACK_RESULT = 'SET_TRACK_RESULT';
export const SET_GENRE = 'SET_GENRE';
export const SET_VALENCE = 'SET_VALENCE';
export const SET_INTSRUMENTALNESS = 'SET_INSTRUMENTALNESS';
export const SET_ENERGY = 'SET_ENERGY';
export const SET_SELECTION = 'SET_SELECTION';
