export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_EXPIRES_IN = 'EXPIRES_IN';
export const SET_LOGIN = 'SET_LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_LOGOUT = 'SET_LOGOUT';

export const GET_SONG_RECOMMENDATION_REQUEST =
  'GET_SONG_RECOMMENDATION_REQUEST';
export const GET_SONG_RECOMMENDATION_SUCCESS =
  'GET_SONG_RECOMMENDATION_SUCCESS';
export const GET_SONG_RECOMMENDATION_FAILURE =
  'GET_SONG_RECOMMENDATION_FAILURE';

export const GET_USERS_PLAYLIST_REQUEST = 'GET_USERS_PLAYLIST_REQUEST';
export const GET_USERS_PLAYLIST_SUCCESS = 'GET_USERS_PLAYLIST_SUCCESS';
export const GET_USERS_PLAYLIST_FAILURE = 'GET_USERS_PLAYLIST_FAILURE';

export const GET_USERS_TOP_ARTISTS_REQUEST = 'GET_USERS_TOP_ARTISTS_REQUEST';
export const GET_USERS_TOP_ARTISTS_SUCCESS = 'GET_USERS_TOP_ARTISTS_SUCCESS';
export const GET_USERS_TOP_ARTISTS_FAILURE = 'GET_USERS_TOP_ARTISTS_FAILURE';

export const PLAY_CONTEXT_REQUEST = 'PLAY_CONTEXT_REQUEST';
export const PLAY_CONTEXT_SUCCESS = 'PLAY_CONTEXT_SUCCESS';
export const PLAY_CONTEXT_FAILURE = 'PLAY_CONTEXT_FAILURE';

export const PAUSE_CONTEXT_REQUEST = 'PAUSE_CONTEXT_REQUEST';
export const PAUSE_CONTEXT_SUCCESS = 'PAUSE_CONTEXT_SUCCESS';
export const PAUSE_CONTEXT_FAILURE = 'PAUSE_CONTEXT_FAILURE';

export const GET_ME_REQUEST = 'GET_ME_REQUEST';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILURE = 'GET_ME_FAILURE';
